### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by comradekingu** [elementary/store#130]
AGPLv3+ preferred to get the network protection.

**Comment by btkostner** [comment]
@cassidyjames I wrote most of the code, but it's under the @elementary org. Is AGPLv3+ ok?

**Comment by cassidyjames** [comment]
@btkostner yep, AGPLv3+ makes sense.

**Comment by btkostner** [comment]
Alright. I'm traveling right now, but PRs welcome! I'll get to it on Friday otherwise (hopefully)
