### ISSUE TITLE
Add Ukrainian language, please

### ISSUE THREAD

**Issue by IhorHordiichuk** [elementary/store#131]
Actually, all request is in the header. If I understand properly if the language will be added to the Store page, it will be automatically added to locales on Weblate, so then I can translate it.

**Comment by cassidyjames** [comment]
@btkostner where do translated language codes come from?

**Comment by btkostner** [comment]
You can add it here and then _I think_ the update action should generate the needed files 

https://github.com/elementary/store/blob/master/config/config.exs#L28

**Comment by IhorHordiichuk** [comment]
I'll do this in few minutes. Hope this will not broke anything.

**Comment by btkostner** [comment]
Sounds good. I'll be home tonight and review the PR

**Comment by btkostner** [comment]
@cassidyjames If you go to weblate, you should be able to add the language. That way we can translate it before we add it as an option

**Comment by IhorHordiichuk** [comment]
I have no permission to do this. And in Slack, you told me "Ahh, the store only has a hard set of languages for it. You'll need to open a PR to add a Ukrainian line here https://github.com/elementary/store/blob/master/config/config.exs#L28"

**Comment by cassidyjames** [comment]
@IhorHordiichuk if you hit the Edit button on that file, GitHub should create a fork on your account and then you can propose the addition of the Ukrainian language code.

@btkostner apparently I don't have permissions in Weblate to add languages, or I just can't figure out how to… :sweat_smile:

**Comment by btkostner** [comment]
The language needs to be added to the store to show up in the language list, but it also needs to be in weblate so you can translate it.

Should be available in weblate now: https://l10n.elementary.io/projects/store/email/uk/

**Comment by IhorHordiichuk** [comment]
Thank you! It is.

**Comment by IhorHordiichuk** [comment]
Only 34 strings out of 111.

**Comment by btkostner** [comment]
Sorry about that, I forgot to add the other components (pages.) Should be good now

**Comment by IhorHordiichuk** [comment]
That's nothing. Thank you! All of them are landed.
