### ISSUE TITLE
Navigation bar, youtube missing

### ISSUE THREAD

**Issue by Xristodoulos99** [elementary/store#165]
" On the website, navigating to different pages i realised that the youtube link is missing from some of the page's navigation, like Developer and Store. I dont see a reason for it to be intentionally not there so i would guess it needs addressing

Thanks. "

I have been redirected here since it is a different project.

Could i fix it?

**Comment by btkostner** [comment]
So, this is an Elixir project that uses the Phoenix framework. The templates used for rendering the website are in [this folder](https://github.com/elementary/store/tree/master/lib/store_web/templates), with the actual primary navigation file being [here](https://github.com/elementary/store/blob/master/lib/store_web/templates/layout/primary-nav.html.leex).

For the most part, it's just HTML so you shouldn't have to worry about any weirdness. You can copy in the YouTube link from viewing the source at https://blog.elementary.io/.

**Comment by cassidyjames** [comment]
YouTube link fixed in #166
