### ISSUE TITLE
Show selected states on product listings

### ISSUE THREAD

**Issue by cassidyjames** [elementary/store#18]
e.g. the selected color and size should be bolded or highlighted somehow so you can be confident in what's selected.

**Comment by btkostner** [comment]
It had a little background. Not sure why that broke, but I added it again. It's pretty small though. Any better ideas? Maybe underline the text too?

![image](https://user-images.githubusercontent.com/3385679/103623178-f9828780-4ef4-11eb-9445-02fcbb0baca1.png)

**Comment by cassidyjames** [comment]
@btkostner that background works for me
