### ISSUE TITLE
Drop qty from product listing

### ISSUE THREAD

**Issue by cassidyjames** [elementary/store#20]
This could help clean up the product listings and allow a better call-to-action for adding to the cart.

I don't know how realistic it is that people will want to buy multiple identical products, and even so, they can add a product to their cart again or modify the quantity from the cart page.

**Comment by danrabbit** [comment]
I guess we should look at printful orders and just make sure that this isn't a common thing

**Comment by btkostner** [comment]
From my very scientific polling of random printful orders (about 50 or so), about 5 of them had products with quantities more than 1. Mostly mugs from what I saw.

I think dropping the quantity from the product page would be cleaner. That redirects the user to the cart page, which will have a quantity adjustment input there.

**Comment by btkostner** [comment]
Closing this because it's done
