### ISSUE TITLE
Product photos shouldn't be dimmed until hovered

### ISSUE THREAD

**Issue by cassidyjames** [elementary/store#24]
Looks like it's just some default link styling, but it makes all the products look washed out. We could invert the logic and have them dim when hovered if we want a hover effect.

**Comment by btkostner** [comment]
Updated to be `opacity: 1` all the time. I was going to add a background on focus but some images have white backgrounds which make it pretty weird. It currently just has the browser built in focus effect, which isn't a bad thing.
