### ISSUE TITLE
Fit more products across smaller display widths

### ISSUE THREAD

**Issue by cassidyjames** [elementary/store#25]
Right now we only show one product photo across phones up to pretty wide viewports, then it snaps to 3 across. I think we could show more across to require less scrolling around here.

**Comment by btkostner** [comment]
I added a 2 column breakpoint at 600px

![image](https://user-images.githubusercontent.com/3385679/103616839-63e1fa80-4eea-11eb-9a2f-792b8fb2dde4.png)

![image](https://user-images.githubusercontent.com/3385679/103616861-72c8ad00-4eea-11eb-9510-2bc6db0adf21.png)
