### ISSUE TITLE
Text in the shipping address entry is invisible in dark style

### ISSUE THREAD

**Issue by ryonakano** [elementary/store#50]
## What Happened

https://user-images.githubusercontent.com/26003928/109093214-56fbbd80-775b-11eb-9948-cfc087a248b0.mov

Text in the shipping address entry is invisible if your system is using dark style.

## Expected Behavior

Text in the shipping address entry should be visible—set the font color in the entry black or set the entry fill color black.

## Steps to Reproduce

1. Add some product to the cart
2. Check your cart
3. See the error

## Platform Information

- macOS 11.2.1
- Google Chrome 88.0.4324.192
- MacBook Air M1, 2020

**Comment by btkostner** [comment]
I adjusted the inputs to look better in dark mode. This should fix the color issue as well.
