### ISSUE TITLE
Weblate translation

### ISSUE THREAD

**Issue by hugok79** [elementary/store#61]
Store translation has been blocked in weblate for some time...

**Comment by hugok79** [comment]
Store is now fully translated in Portuguese(pt).... as well as the entire elementary OS project.

https://l10n.elementary.io/languages/pt/

**Comment by btkostner** [comment]
Looking back into this, it looks like translations got fixed some time in between and have been working fine all automated. I'll set a reminder to double check this in 7 days to make sure it still works.

**Comment by btkostner** [comment]
Seems to be working fine. Closing.

**Comment by hugok79** [comment]
https://elementary.io/pt/store/

No Portuguese here....

**Comment by btkostner** [comment]
This repository is for store.elementary.io. You can select the language here: https://store.elementary.io/language

**Comment by hugok79** [comment]
yes, now i can see in portuguese.  so the store link on the main site do not correctly redirect to the store....

**Comment by btkostner** [comment]
Yes, this current store is not released publicly yet
