### ISSUE TITLE
Site seems to repeatedly refresh

### ISSUE THREAD

**Issue by zeebok** [elementary/store#74]
## What Happened
While browsing the goods for sale, the page seems to slowly and repeatedly refresh. I can't tell if it is after so much time or loading slow but the blue loading bar was filling fairly slowly so I could watch the refresh coming. After closing and loading the site again it stopped and I was able to go through with purchasing. Running in a private window seems to have the issue.

## Expected Behavior
The site should finish loading and not interrupt the shopping!

## Steps to Reproduce
In order for me to reproduce after the first time, I needed to open the site from a private window.

1. Go to any page on the store
2. After waiting some time, the page should reload. In most cases the blue loading bar was active and filling before the refresh

## Platform Information
I was using the latest stable Firefox on Windows 10 at the time I saw the issue. I can confirm later if I see the same from eOS.

**Comment by btkostner** [comment]
How good is your internet? And is it stable (no random disconnects)? 

The site uses websockets for most of it so if there is a disconnect then the page might refresh.

Can you press F12, click console, and post any errors you see please

**Comment by zeebok** [comment]
Internet is good, and just tried on a connection at a different location with the same issue.

There are no errors until the moment before the refresh occurs:

`Firefox can’t establish a connection to the server at ws://store.elementary.io/live/websocket?_csrf_token=LCMMDjd7NCgISS4ABh4CDVsFNm9KWgw5hPcYZ0VnZ0KXYjih1Dt73nuI&_track_static%5B0%5D=http%3A%2F%2Fstore.elementary.io%2Fstyles%2Fapp-10b533bb69d7f30c7bbd1a92f2569dca.css%3Fvsn%3Dd&_track_static%5B1%5D=http%3A%2F%2Fstore.elementary.io%2Fscripts%2Fapp-e4c6b704f4ac57a62a571ca7d38083fe.js%3Fvsn%3Dd&_mounts=0&vsn=2.0.0. app-e4c6b704f4ac57a62a571ca7d38083fe.js:1:14271

The connection to ws://store.elementary.io/live/websocket?_csrf_token=NEo4EF0yWgoVMi1pbDY0IgkjFDlITTsVp9WG0y8LGKH13B_GcbVa1yBe&_track_static%5B0%5D=http%3A%2F%2Fstore.elementary.io%2Fstyles%2Fapp-10b533bb69d7f30c7bbd1a92f2569dca.css%3Fvsn%3Dd&_track_static%5B1%5D=http%3A%2F%2Fstore.elementary.io%2Fscripts%2Fapp-e4c6b704f4ac57a62a571ca7d38083fe.js%3Fvsn%3Dd&_mounts=0&vsn=2.0.0 was interrupted while the page was loading. app-e4c6b704f4ac57a62a571ca7d38083fe.js:1:14271
`

**Comment by btkostner** [comment]
That's interesting. It's trying to connect to a non ssl websocket endpoint. Can you double check that the browser is using https when viewing the store.

**Comment by zeebok** [comment]
You called it. When I have the problem I am not on https. What is interesting is that I do use the https everywhere extension so it should've tried to use a secure connection.

**Comment by btkostner** [comment]
Very weird. I'm looking into forcing ssl on the whole elementary.io domain right now. I'm pretty sure there was a reason we didn't, but I can't remember why. Anyway. I'm going to close this issue and once we force ssl this shouldn't be a problem anymore.
