### ISSUE TITLE
Unable to purchase laptop sleeve

### ISSUE THREAD

**Issue by asonix** [elementary/store#75]
## What Happened
I got your email today about the soft launch, and I tried to purchase a T-shirt, a mug, and a laptop sleeve from the store. On the checkout page, I was able to get shipping rates, but the checkout button ended up putting me back on the same page. I've tried in Firefox, Firefox Focus, Brave, and the default Lineage OS browser.

## Expected Behavior
Selecting checkout takes me to a payment page

## Steps to Reproduce

1. Add a Large elementary T shirt to the cart
2. Add an elementary mug to the cart
3. Add a laptop sleeve to the cart
4. On the checkout page, fill in Name, Address Line 1, City, Country, State, Postal Code, and Email
5. Select Get Shipping Rates
6. Select Flat Rate
7. Select Checkout

I'd rather not share my address or email publicly, but I do have a hunch this is a validation error that's not getting surfaced properly if this hasn't been encountered before.

## Platform Information
I'm running Lineage OS 17.1 based on Android 10. I've tried Firefox, Firefox Focus, Brave, and the default Lineage OS browser

**Comment by asonix** [comment]
I have not tried from a desktop browser, but I can do that tomorrow morning

**Comment by btkostner** [comment]
This probably is what you said and some validation error causing the issue.

If you feel comfortable, can you please email your address to blake@elementary.io and I can make sure the error is fixed up for you.

**Comment by asonix** [comment]
I specifically had:
- a large light-blue elementary (the word) shirt
- a light-blue elementary logo mug
- the 13" freya laptop sleve

**Comment by asonix** [comment]
I'll try ordering each separately and seeing if it fails on one

**Comment by asonix** [comment]
it's the laptop sleeve. I was able to purchase the t-shirt and the mug individually, but not the laptop sleeve

**Comment by asonix** [comment]
I just tried every laptop sleeve at 13", and the freya laptop sleeve at 15", and encountered the same issue for those

**Comment by btkostner** [comment]
An update, this issue is due to how we designed the laptop sleeves with multiple layers in printful. We are working on compressing them to a single file and updating the products. Once that is done you should be able to order laptop sleeves without an issue.

**Comment by btkostner** [comment]
Alright. All laptop sleeves are updated now, so you should be good now. Thank you for your help debugging this issue!
